#ifndef CMEAUDITTRAIL_AUDITTRAILSESSIONLEVELREJECT_H
#define CMEAUDITTRAIL_AUDITTRAILSESSIONLEVELREJECT_H


class AuditTrailSessionLevelReject {

};


#endif //CMEAUDITTRAIL_AUDITTRAILSESSIONLEVELREJECT_H
