#ifndef CMEAUDITTRAIL_AUDITTRAILORDERCANCELREQUEST_H
#define CMEAUDITTRAIL_AUDITTRAILORDERCANCELREQUEST_H


class AuditTrailOrderCancelRequest {

};


#endif //CMEAUDITTRAIL_AUDITTRAILORDERCANCELREQUEST_H
