#ifndef CMEAUDITTRAIL_AUDITTRAILEXECRPTACKNOWLEDGMENT_H
#define CMEAUDITTRAIL_AUDITTRAILEXECRPTACKNOWLEDGMENT_H


class AuditTrailExecRptAcknowledgment {

};


#endif //CMEAUDITTRAIL_AUDITTRAILEXECRPTACKNOWLEDGMENT_H
