#ifndef CMEAUDITTRAIL_AUDITTRAILBUSINESSLEVELREJECT_H
#define CMEAUDITTRAIL_AUDITTRAILBUSINESSLEVELREJECT_H


class AuditTrailBusinessLevelReject {

};


#endif //CMEAUDITTRAIL_AUDITTRAILBUSINESSLEVELREJECT_H
